# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Syndic8
version:      0.01
version_from: lib/Net/Syndic8.pm
installdirs:  site
requires:
    HTML::WebDAO:                  0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
